const Cars = [
    {
        id: 'avt780',
        name: 'AVENTADOR LP 780-4 ULTIMAE',
        model: 'AVENTADOR',
        maxspeed: '355 km/h',
        power: '780 CV (574 kW) at 8,500 rpm',
        acceleration: '2.8 s',
        img: 'https://www.lamborghini.com/sites/it-en/files/DAM/lamborghini/facelift_2019/model_detail/aventador/Ultimae/menu_aven_ultimae.png',
        desc: 'it takes time to become timeless',
    },
    {
        id: 'avt780lp',
        name: 'AVENTADOR LP 780-4 ULTIMAE ROADSTER',
        model: 'AVENTADOR',
        maxspeed: '355 km/h',
        power: '780 CV (574 kW) at 8,500 rpm',
        acceleration: '2.9 s',
        img: 'https://www.lamborghini.com/sites/it-en/files/DAM/lamborghini/facelift_2019/model_detail/aventador/ultimae_roadster/menu_aven_ulti_rds.png',
        desc: 'it takes time to become timeless',
    },
    {
        id: 'hrcsrt',
        name: 'HURACÁN STERRATO',
        model: 'HURACÁN',
        maxspeed: '260 km/h',
        power: '610 CV / 449 kW',
        acceleration: '3.4 s',
        img: 'https://www.lamborghini.com/sites/it-en/files/DAM/lamborghini/facelift_2019/model_detail/huracan/sterrato/menu/huracan_sterrato_menu_01.png',
        desc: 'Beyond the concrete',
    },
    {
        id: 'hrctnc',
        name: 'HURACÁN TECNICA',
        model: 'HURACÁN',
        maxspeed: '325 km/h',
        power: '640 CV / 470 kW',
        acceleration: '3.2 s',
        img: 'https://www.lamborghini.com/sites/it-en/files/DAM/lamborghini/facelift_2019/model_detail/huracan/tecnica/menu_hura_tecnica_01.png',
        desc: 'Take all your souls to drive',
    },
    {
        id: 'hrcsto',
        name: 'HURACÁN STO',
        model: 'HURACÁN',
        maxspeed: '310 km/h',
        power: '640 CV / 470 kW',
        acceleration: '3.0 s',
        img: 'https://www.lamborghini.com/sites/it-en/files/DAM/lamborghini/facelift_2019/model_detail/huracan/sto/menu_huracan_sto.jpg',
        desc: 'Take all your souls to drive',
    },
    {
        id: 'hrcevo',
        name: 'HURACÁN EVO',
        model: 'HURACÁN',
        maxspeed: '>325 km/h',
        power: '640 CV / 470 kW',
        acceleration: '2.9 s',
        img: 'https://www.lamborghini.com/sites/it-en/files/DAM/lamborghini/facelift_2019/model_detail/menu/09_09/menu_huracan_evo.jpg',
        desc: 'Take all your souls to drive',
    },

    {
        id: 'urss',
        name: 'URUS S',
        model: 'URUS',
        maxspeed: '305 km/h',
        power: '666 CV / 490 kW',
        acceleration: '3.5 s',
        img: 'https://www.lamborghini.com/sites/it-en/files/DAM/lamborghini/facelift_2019/model_detail/gateway_urus/performante/2022/menu/silhouette_menu_01.png',
        desc: 'Take all your souls to drive',
    },
    {
        id: 'urpfm',
        name: 'URUS PERFORMANTE',
        model: 'URUS',
        maxspeed: '306 km/h',
        power: '666 CV / 490 kW',
        acceleration: '3.3 s',
        img: 'https://www.lamborghini.com/sites/it-en/files/DAM/lamborghini/facelift_2019/model_detail/gateway_urus/performante/2022/menu/silhouette_menu_01.png',
        desc: 'FOR BAR RAISERS ONLY',
    },

    {
        id: 'lmtsr1',
        name: 'COUNTACH LPI 800-4',
        model: 'LIMITED SERIES',
        maxspeed: '355 km/h',
        power: '814 CV / 599 kW',
        acceleration: '2.8 s',
        img: 'https://www.lamborghini.com/sites/it-en/files/DAM/lamborghini/facelift_2019/model_detail/countach/menu/menu_countach_lpi_01.png',
        desc: 'FUTURE IS OUR LEGACY',
    },
    {
        id: 'lmtsr2',
        name: 'SIAN FKP 37',
        model: 'LIMITED SERIES',
        maxspeed: '355 km/h',
        power: '819 CV / 602 kW',
        acceleration: '<2.8 s',
        img: 'https://www.lamborghini.com/sites/it-en/files/DAM/lamborghini/facelift_2019/model_detail/menu/09_09/menu_sianFKP37.png',
        desc: 'Ahead of its time',
    },
    //

    {
        id: 'lmtsr2',
        name: 'TERZO MILLENNIO',
        model: 'CONCEPT',
        maxspeed: '355 km/h',
        power: '819 CV / 602 kW',
        acceleration: '<2.8 s',
        img: 'https://www.lamborghini.com/sites/it-en/files/DAM/lamborghini/facelift_2019/model_detail/menu/09_09/menu_terzo_millennio.png',
        desc: 'Ahead of its time',
    },
    {
        id: 'lmtsr2',
        name: 'ASTERION',
        model: 'CONCEPT',
        maxspeed: '355 km/h',
        power: '819 CV / 602 kW',
        acceleration: '<2.8 s',
        img: 'https://www.lamborghini.com/sites/it-en/files/DAM/lamborghini/facelift_2019/model_detail/menu/09_09/menu_asterion.png',
        desc: 'Ahead of its time',
    },
    {
        id: 'lmtsr2',
        name: 'SIAN FKP 37',
        model: 'CONCEPT',
        maxspeed: '355 km/h',
        power: '819 CV / 602 kW',
        acceleration: '<2.8 s',
        img: 'https://www.lamborghini.com/sites/it-en/files/DAM/lamborghini/facelift_2019/model_detail/menu/09_09/menu_estoque.png',
        desc: 'Ahead of its time',
    },
];

export { Cars };
